export default {
  ADD_FRIEND: "ADD_FRIEND",
  REMOVE_FRIEND: "REMOVE_FRIEND",
  SET_FRIENDS: "SET_FRIENDS",
  SET_CHAT: "SET_CHAT",
  ADD_MESSAGE: "ADD_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  EDIT_MESSAGE: "EDIT_MESSAGE",
  ADD_USER_MESSAGE: "ADD_USER_MESSAGE",
  REMOVE_USER_MESSAGE: "REMOVE_USER_MESSAGE",
  NOTIFY_DELETED_CHAT: "NOTIFY_DELETED_CHAT",
  SET_USER: "SET_USER",
};
